name: New CICD_Slack_Notif
on:
  push:
    branches:
      - dev
      - main

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Slack for QA
        uses: actions/checkout@v3
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          Token: QA_TOKEN
          Canal: QA_SLACK
      - name: Setting Slack for PRD
        uses: actions/checkout@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          Token: PRD_TOKEN
          Canal: PRD_SLACK
      - name: Send message to Slack API
        run: echo "canal $Canal token $Token"
