name: New CICD_Slack_Notif
on:
  push:
    branches:
      - dev
      - main

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Slack notify id
        uses: archive/github-actions-slack@v2.3.2
        id: notify
      - name: Send message to Slack API to QA
        if: ${{ github.ref == 'refs/heads/dev' }}
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_QA }}
          slack-channel: C033JLXCSES
          slack-text: test QA
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
      - name: Send message to Slack API to PRD
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: archive/github-actions-slack@v2.3.2
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN_QA }}
          slack-channel: C033JLXCSES
          slack-text: test PRD
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
