name: New CICD_Slack_Notif
on:
  push:
    branches:
      - dev
      - main

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Slack notify id
        run: echo "QA - canal $Canal token $Token"
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          Token: QA_TOKEN
          Canal: QA_SLACK
      - name: Setting Slack notify id
        run: echo "PRD - canal $Canal token $Token"
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          Token: PRD_TOKEN
          Canal: PRD_SLACK
      - name: Send message to Slack API to QA
        uses: archive/github-actions-slack@v2.3.2
        id: notify
        with:
          slack-function: send-message 
          slack-bot-user-oauth-access-token: ${{ env.Token }}
          slack-channel: ${{ env.Canal }}
          slack-text: test 
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
