name: New CICD_Slack_Notif
on:
  push:
    branches:
      - dev
      - main

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Setting Slack for QA
        run: export canal=${{ Canal }}; export token=${{ Token }}
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          Token: QA_TOKEN
          Canal: QA_SLACK
      - name: Setting Slack for PRD
        run: export canal=${{ Canal }}; export token=${{ Token }}
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          Token: PRD_TOKEN
          Canal: PRD_SLACK
      - name: Send message to Slack API to QA
        run: echo "canal $canal token $Token"
