name: testif
on:
  push:
    branches: 
      - main
      - dev

jobs:
  on-failure-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Settings for QA
        run: echo "${{ env.slack-channel }}"
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          slack-channel: QA_SLACK
      - name: Settings for UAT
        run: echo "${{ env.slack-channel }}"
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          slack-channel: UAT_SLACK
      - name: Result from "Send Message to DEV"
        run: echo "Notificando por slack ${{ env.slack-channel }} en rama ${{ github.ref }}"

