name: testif
on:
  push:
    branches: 
      - main
      - dev

if: ${{ github.ref == 'refs/heads/dev' }}
env:
  slack-channel: QA_SLACK
if: ${{ github.ref == 'refs/heads/main' }}
env:
  slack-channel: UAT_SLACK

jobs:
  on-failure-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Result from "Send Message to DEV"
        run: echo "Notificando por slack ${{ env.slack-channel }} en rama ${{ github.ref }}"

